[package]
name = "geometry-wars"
version = "0.2.0"
edition = "2021"

[dependencies]
ordered-float = "3.4.0"
num = "0.4.0"
bevy = { version = "0.10" }
bevy_egui = "0.20"
egui_dnd = "0.3.0"
bevy_rapier2d = { version = "0.21.0", features = ["debug-render-2d"] }
bevy_prototype_lyon = "0.8.0"
#bevy_hanabi = { version = "0.6", default-features = false, features = [ "2d" ] }
bevy_tweening = "0.7"
strum = "0.24"
strum_macros = "0.24"
rand = "0.8.5"
rand_distr = "0.4.3"
bevy-debug-text-overlay = "5.0.0"
geo = "0.24.0"

# Enable a small amount of optimization in debug mode
# [profile.dev]
# opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3
