[package]
name = "geometry-wars"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.9.1", features = ["dynamic"] }
bevy_rapier2d = { version = "0.20.0", features = ["debug-render-2d"] }
bevy_prototype_lyon = "0.7.0"
bevy_hanabi = "0.5.0"
bevy-inspector-egui = "0.17.0"
strum = "0.24"
strum_macros = "0.24"
rand = "0.8.5"
rand_distr = "0.4.3"
# bevy_stat_bars = "0.3"
bevy-debug-text-overlay = "4.0.1"
# kayak_ui = { git="https://github.com/StarArawn/kayak_ui", rev="108affb36101e0c06fd9a28aa80224323365227d", features = ["bevy_renderer"] }

# Enable a small amount of optimization in debug mode
# [profile.dev]
# opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3
